# NumPy

- Es una extensión de python para trabajar con vectores y matrices
- Es una librería de algebra lineal muy rápida
- Es bastante recomendable instalar Python con distribucion Anaconda o en su defecto utilizar colab
- Si tienes instalado la distribución Anaconda, ya por si sola tendria los datos necesarios para usar la libria numpy
- En caso de no tener instalado anaconda ejecutar en la terminal: pip install numpy


## Nunpy arrays

In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4]

In [3]:
array = np.array(lista)

In [4]:
array

array([1, 2, 3, 4])

In [5]:
lista2 = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
array2 = np.array(lista2)

In [8]:
#Creando arrays
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Numpy arrays - arange, zeros, ones, linspace, eye

In [9]:
import numpy as np

In [10]:
array = np.arange(5)#Generar un array con metodo arange

In [11]:
array #secuencia de valores desde 0 a 5-1

array([0, 1, 2, 3, 4])

In [12]:
np.arange(2,10)#Secuencia de numeros desde 2 a 10-1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2,10,2)#En este caso crea la secuencia con un step de 2 desde el 2 hasta 10-1

array([2, 4, 6, 8])

In [14]:
np.arange(3,20,2)#En este caso crea la secuencia con un step de 3 desde el 3 hasta 20-1

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
np.zeros(3)#Genera un array de una dimension con puro ceros dependiendo a la cantidad dada en este caso 3

array([0., 0., 0.])

In [24]:
np.zeros((3,6))#Genera un array de 2 dimensiones y rellenado con ceros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.ones(3)#Genera un array de una dimension con puro 1 dependiendo a la cantidad dada en este caso 3

array([1., 1., 1.])

In [27]:
np.ones((3,6))#Genera un array de 2 dimensiones y rellenado con unos

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
np.linspace(5, 8, 50)#Genera un array con los siguientes parametros:
                    #5 numero incial hasta 8 numero final y generando 50 numeros entre estos 2

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [30]:
np.linspace(3, 9, 20)#Genera un array de 20 elemntos entre 3 y 9

array([3.        , 3.31578947, 3.63157895, 3.94736842, 4.26315789,
       4.57894737, 4.89473684, 5.21052632, 5.52631579, 5.84210526,
       6.15789474, 6.47368421, 6.78947368, 7.10526316, 7.42105263,
       7.73684211, 8.05263158, 8.36842105, 8.68421053, 9.        ])

In [31]:
np.eye(5)#Geenra una matriz cuadrada de tanto filas como columnas el mismo valor

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Numpy arrays - números aleatorios - rand y randn

In [33]:
import numpy as np

In [34]:
np.random.rand(5)#Genera un array de una dimension con numeros aletorios con 5 elmentos

array([0.4639809 , 0.51306099, 0.41526211, 0.95912875, 0.52732904])

In [38]:
np.random.rand(2,5)#Generar un array de 2 dimensions con numeros aletorios de 2 filas y 3 columnas

array([[0.45493758, 0.34448707, 0.63522551, 0.7757742 , 0.61219724],
       [0.74313564, 0.88862208, 0.9871468 , 0.71989546, 0.47190354]])

In [39]:
np.random.randn(4)#Genera un array de una dimension con numeros aletorios con 4 elmentos

array([-2.36491019,  0.13193467, -1.25583642,  0.04534941])

In [41]:
np.random.randn(4, 5)#Generar un array de 2 dimensions con numeros aletorios de 4 filas y 5 columnas

array([[ 0.73152001,  1.14938719,  0.54317727,  1.0354561 ,  0.9274449 ],
       [ 1.81165519, -0.01649804, -0.57600602, -0.62046719, -0.41885049],
       [-1.16305567, -1.39692529,  1.65881986, -1.15697774,  1.90583692],
       [ 0.1074165 ,  1.09783936, -0.55078462,  1.19271924, -0.2209032 ]])

## Numpy arrays - números aleatorios enteros, randint 

In [42]:
import numpy as np

In [47]:
np.random.randint(1,20)#Genera un número aletorio entre 1 y 20-1

6

In [48]:
np.random.randint(1,20,5)#Genera 5 numeros aleatorios entre 1 y 20-1

array([ 9, 13, 15, 12,  9])

## Numpy arrays - reshape

In [49]:
import numpy as np

In [70]:
array = np.random.randint(1,100, 25)#Genera un array de 25 elementos de numeros entre 1 y 100

In [71]:
array

array([14,  3, 91, 88, 10, 83, 39, 15, 71, 65, 77, 78, 42, 89, 76, 44, 33,
       67, 18, 75, 27, 49, 71, 24, 17])

In [72]:
matriz = array.reshape(5,5)#Reforma el array a como querramos simepre y cuando las multiplicaion de las filas y columnas den el
                            #numero de elemetos del array, en este caso 25 = 5*5

In [74]:
matriz#MAtriz de 2 deimensiones de 5 filas y 5 columnas

array([[14,  3, 91, 88, 10],
       [83, 39, 15, 71, 65],
       [77, 78, 42, 89, 76],
       [44, 33, 67, 18, 75],
       [27, 49, 71, 24, 17]])

## Numpy arrays - max y min

In [75]:
import numpy as np

In [76]:
array = np.random.randint(1,100,50)#Genera un array con 50 elementos entre 1 y 100

In [77]:
array

array([ 1, 72, 36, 38,  8, 47, 95, 23, 97, 16, 76, 55, 32, 12, 65, 67, 40,
       76, 40, 33, 13, 31, 21, 21, 89, 75, 66, 88,  2, 58, 80, 97, 92, 14,
       33, 52, 81, 74, 80, 54, 45, 33, 64, 78, 46, 90, 80, 65, 56, 75])

In [86]:
#Saca el mayor variable del array en otra variable
valor_maximo = array.max()
valor_maximo

97

In [87]:
#Posicion en el array del mayor valor
posicion_valor_maximo = array.argmax()
posicion_valor_maximo

8

In [82]:
#Saca la menor variable del array en otra variable
valor_minimo = array.min()
valor_minimo

1

In [88]:
#Posicion en el array del valor minimo
posicion_valor_minimo = array.argmin()
posicion_valor_minimo

0

## Numpy - Indexacion en arrays

In [89]:
import numpy as np

In [90]:
array = np.arange(0,10)

In [91]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
array [0]#Idenxacion de Arrays

0

In [93]:
array[1]#Segundo elemnto

1

In [94]:
array[-1]#Elemento en la ultima posicion

9

In [95]:
array[2:4]#Muestra elementos entre posicion 2 a la poscion 4-1

array([2, 3])

In [96]:
array[5:]#Muestra datos desde la 6ta posicion hata la ultima

array([5, 6, 7, 8, 9])

In [97]:
array[:4]#El primer elmento hasta la posicion 4 -1

array([0, 1, 2, 3])

In [99]:
#Copia del Array con la funcion copy()
array2 = array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
#Si se altera la copia del array
array2[0] = 100
array2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [104]:
#El original conserva sus datos
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Numpy - Indexacion en arrays de 2 a mas dimensiones

In [105]:
import numpy as np

In [107]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
array[0]

array([1, 2, 3])

In [112]:
print(array[:2])
array2 = array[:2]

[[1 2 3]
 [4 5 6]]


In [113]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
array[0][0]

1

In [116]:
array[1,1]

5

In [117]:
array[:,0]#Mostar la primera columna

array([1, 4, 7])

In [119]:
array[:1]#Mostrar la primera fila

array([[1, 2, 3]])

In [124]:
array[:,:2]#Muestra Las columnas desde esl inicio hasta 2-1

array([[1, 2],
       [4, 5],
       [7, 8]])

In [125]:
array[:2,:]#Muestra las filas desde el inicio hasta 2-1

array([[1, 2, 3],
       [4, 5, 6]])

## Numpy - Seleccionar elementos de un array segun una condicion

In [126]:
import numpy as np

In [130]:
array = np.arange(0,10)

In [131]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
condicion = array > 5# Inplementa operadores de comparacion sobre todos los elementos del array

In [133]:
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [139]:
array[condicion]#Muestra cuales son los elemtnos que cumples la condicion

array([6, 7, 8, 9])

In [137]:
array6 = array[array < 6]
array6

array([0, 1, 2, 3, 4, 5])

In [141]:
array[array % 2 ==0]#Muestra solo los elemtos pares gracias  a la condicion

array([0, 2, 4, 6, 8])

## Numpy - Operaciones sobre los arrays

Las operacions afectan sobre todos los elementos del array

In [142]:
import numpy as np

In [143]:
array = np.arange(0,10)

In [144]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [146]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [147]:
array + 40

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [148]:
array - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [153]:
array2 = np.arange(5,15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [154]:
#Operaciones entre 2 arryas los ejecuta con elementos en las mismas posiciones
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [156]:
array2 * array

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [157]:
np.max(array)

9

In [158]:
np.min(array)

0